### ISSUE TITLE
Auto warmup not working on IOS build

### ISSUE THREAD

**Issue by H-man** [X-Crew/Morpeh#52]
IOS build crashes at startup with this message:

```
ExecutionEngineException: Attempting to call method 'Morpeh.TypeIdentifier`1[[MyTestComponent, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]::Warmup' for which no ahead of time (AOT) code was generated.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <00000000000000000000000000000000>:0 
  at Morpeh.WorldExtensions.InitializationDefaultWorld () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.UnhandledExceptionHandler:PrintException(String, Exception)
UnityEngine.UnhandledExceptionHandler:HandleUnhandledException(Object, UnhandledExceptionEventArgs)
System.UnhandledExceptionEventHandler:Invoke(Object, UnhandledExceptionEventArgs)
```

I fixed this wrapping these 'warm types' codes in InitializationDefaultWorld method with !UNITY_IOS define. Not sure if this problem exists on other AOT platforms too

**Comment by BenjaminMoore** [comment]
@H-man is it develop build or release?

**Comment by H-man** [comment]
Release build, stripping level set to 'low' and Script Call Optimization set to 'Fast but no Exceptions'

Not sure what that warm types does, but it works perfectly on IOS without that

**Comment by BenjaminMoore** [comment]
It must be work okay.
Warming up is needed only for components that are created through the inspector UniversalProvider or Singleton.
In the latest develop, the exception is replaced with a warning so that the user understands which types are not warmed up.
Typically, types that are not used anywhere in the code are not warmed up.

**Comment by H-man** [comment]
Tried today using latest Develop branch and no crashing anymore. I think this issue can be closed now.
