### ISSUE TITLE
License doesn't show as MIT on GitHub page

### ISSUE THREAD

**Issue by jeffcampbellmakesgames** [X-Crew/Morpeh#8]
## Summary

Hi there, I noticed a very small issue when reading the GitHub page for this library. Even though the license reads as an MIT license for some reason GitHub is not picking that up and indicating you should read the contents for more details.

![image](https://user-images.githubusercontent.com/1663648/75372131-499dc000-58c8-11ea-8017-18769a8d81c8.png)

Though its a very small thing, when other people read this page or view it in their search results this project would not show as having an MIT license. I've had this problem before and the way I've usually resolved it is to delete the existing license and re-add it through the GitHub website. Its usually some very slight, inane formatting or naming issue that causes it to not show correctly..

I hope this is helpful for you!

**Comment by BenjaminMoore** [comment]
Thanks for contibuting @jeffcampbellmakesgames.
I fixed this minor oversight.
